# Generated by Django 4.2.2 on 2023-06-17 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cactus', '0002_rename_categoy_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cactus.plant')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
