# Generated by Django 4.2.2 on 2023-06-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items_Pedido',
        ),
    ]
