# Generated by Django 4.2.2 on 2023-06-27 11:24

from django.db import migrations



def create_default_group(apps,schema_editor):
        
        Group = apps.get_model('auth','Group')
        Group.objects.get_or_create(name='Client')
        Group.objects.get_or_create(name='Admin')
        


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.RunPython(create_default_group),
        
    ]


