# Generated by Django 4.2.2 on 2023-06-27 12:07

from django.db import migrations
from django.contrib.auth.models import Permission,Group

def create_permissions_User(apps, schema_editor):
    # Create new permissions
    group = Group.objects.get(name='Client')
    view_permission = Permission.objects.get(codename='view_user')
    change_permission = Permission.objects.get(codename='change_user')
    delete_permission = Permission.objects.get(codename='delete_user')
    
    group.permissions.add(view_permission, change_permission, delete_permission)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230627_0733'),
    ]

    operations = [
        migrations.RunPython(create_permissions_User),
    ]
