# Generated by Django 4.2.2 on 2024-02-21 04:42

from django.db import migrations
from django.contrib.auth import get_user_model

def create_user(apps,schema_editor):
    User = get_user_model()
    User.objects.create_superuser('admin','mangelryujin@gmail.com','admin','admin','admin')
    
    
class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_last_name_alter_user_name"),
    ]

    operations = [
        migrations.RunPython(create_user),
    ]
