# Generated by Django 4.2.2 on 2023-06-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoy_name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la categoria')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la planta')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_image/', verbose_name='Imagen del producto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cactus.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
            },
        ),
    ]
